Rewrite some part of the code to make it easier to read.
openkstore/kstore pull request #1
Opened 2018-10-02 14:41 UTC by OlivierPitton

2018-10-02 15:39 UTC, rodolpheDdB approved these changes

2018-10-03 08:32 UTC, EstebanGonzal approved these changes

2018-10-03 08:33 UTC, rodolpheDdB approved these changes

2018-10-03 09:17 UTC, EricIndexima requested changes
We may want to create a range just to have access to the bitmap, and get the power of its expressiveness. There must a empty constructor range.

2018-10-08 13:56 UTC, EricIndexima approved these changes

2018-10-08 14:04 UTC, merged